version: '3.4'

# Visual Studio Code doesn't look at the compose.override.yml file (https://github.com/Microsoft/vscode-docker/issues/379).
# For now, set all debug environment settings here.

services:
  airportmesh.checkin:
    image: airport-mesh/check-in-service:latest
    build: CheckInService
    ports:
      - "5000:80"
    environment:
      - AIRPORTMESH_STORAGE_ACCOUNT_NAME=${AIRPORTMESH_STORAGE_ACCOUNT_NAME}
      - AIRPORTMESH_STORAGE_ACCOUNT_KEY=${AIRPORTMESH_STORAGE_ACCOUNT_KEY}

  airportmesh.homelandsecurity:
    image: airport-mesh/homeland-security-service:latest
    build: HomelandSecurityService
    environment:
      - AIRPORTMESH_STORAGE_ACCOUNT_NAME=${AIRPORTMESH_STORAGE_ACCOUNT_NAME}
      - AIRPORTMESH_STORAGE_ACCOUNT_KEY=${AIRPORTMESH_STORAGE_ACCOUNT_KEY}

  airportmesh.scan:
    image: airport-mesh/scan-service:latest
    build: ScanService
    ports:
      - "5001:80"

  airportmesh.sort:
    image: airport-mesh/sort-service:latest
    build: SortService
    ports:
      - "5002:80"
    volumes:
      - "~/SortOTron:/app/data"
